THIS IS NOT A GITHUB COMMIT OR ANY DOCUMENTATION IN ANYWAY FOR THE PROJECT
<!-- ============================== -->

TO DO LIST
_______

1-- when test are register, saved and it has extra tests and you make a mistake of not completeing atleast
    one raw of extra test and save you will not be able to come back and edit it. (this needs fixs).
2-- <b>Warning</b>: Attempt to read property "role" on string in <b>C:\xampp\htdocs\projects\Hospital-Online\private\views\admin\head_foot\admin-header.view.php</b> on line <b>216</b><br/>
